// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityFlatpickrController from "./activity_flatpickr_controller"
application.register("activity-flatpickr", ActivityFlatpickrController)

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)
import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InterestController from "./interest_controller"
application.register("interest", InterestController)

import MapController from "./map_controller"
application.register("map", MapController)
